// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.fisco.bcos.sdk.v3.client.protocol.model;

public class TransactionAttribute {
    private TransactionAttribute() {}

    public static final int EVM_ABI_CODEC = 0x1;
    public static final int LIQUID_SCALE_CODEC = 0x2;
    public static final int DAG = 0x4;
    public static final int LIQUID_CREATE = 0x8;
}
