codecov:
  branch: "*"
coverage:
  ignore:
    - "src/integration-test/**/*"
    - "src/integration-wasm-test/**/*"
  status:
    project:
      default:
        target: "30%"
        threshold: "1%"
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
