// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.fisco.bcos.sdk.client.protocol.model.tars;

import com.qq.tars.protocol.tars.TarsInputStream;
import com.qq.tars.protocol.tars.TarsOutputStream;
import com.qq.tars.protocol.tars.annotation.TarsStruct;
import com.qq.tars.protocol.tars.annotation.TarsStructProperty;
import com.qq.tars.protocol.util.TarsUtil;

@TarsStruct
public class Transaction {
    public static final int LIQUID_SCALE_CODEC = 0x2;
    public static final int LIQUID_CREATE = 0x8;

    @TarsStructProperty(order = 1, isRequire = false)
    public TransactionData data = null;

    @TarsStructProperty(order = 2, isRequire = false)
    public byte[] dataHash = null;

    @TarsStructProperty(order = 3, isRequire = false)
    public byte[] signature = null;

    @TarsStructProperty(order = 4, isRequire = false)
    public long importTime = 0L;

    @TarsStructProperty(order = 5, isRequire = false)
    public int attribute = 0;

    @TarsStructProperty(order = 6, isRequire = false)
    public String source = "";

    public TransactionData getData() {
        return data;
    }

    public void setData(TransactionData data) {
        this.data = data;
    }

    public byte[] getDataHash() {
        return dataHash;
    }

    public void setDataHash(byte[] dataHash) {
        this.dataHash = dataHash;
    }

    public byte[] getSignature() {
        return signature;
    }

    public void setSignature(byte[] signature) {
        this.signature = signature;
    }

    public long getImportTime() {
        return importTime;
    }

    public void setImportTime(long importTime) {
        this.importTime = importTime;
    }

    public int getAttribute() {
        return attribute;
    }

    public void setAttribute(int attribute) {
        this.attribute = attribute;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Transaction() {}

    public Transaction(
            TransactionData data,
            byte[] dataHash,
            byte[] signature,
            long importTime,
            int attribute,
            String source) {
        this.data = data;
        this.dataHash = dataHash;
        this.signature = signature;
        this.importTime = importTime;
        this.attribute = attribute;
        this.source = source;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + TarsUtil.hashCode(data);
        result = prime * result + TarsUtil.hashCode(dataHash);
        result = prime * result + TarsUtil.hashCode(signature);
        result = prime * result + TarsUtil.hashCode(importTime);
        result = prime * result + TarsUtil.hashCode(attribute);
        result = prime * result + TarsUtil.hashCode(source);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Transaction)) {
            return false;
        }
        Transaction other = (Transaction) obj;
        return (TarsUtil.equals(data, other.data)
                && TarsUtil.equals(dataHash, other.dataHash)
                && TarsUtil.equals(signature, other.signature)
                && TarsUtil.equals(importTime, other.importTime)
                && TarsUtil.equals(attribute, other.attribute)
                && TarsUtil.equals(source, other.source));
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transaction(");
        sb.append("data:");
        if (this.data == null) {
            sb.append("null");
        } else {
            sb.append(this.data);
        }
        sb.append(", ");
        sb.append("dataHash:");
        if (this.dataHash == null) {
            sb.append("null");
        } else {
            sb.append(this.dataHash);
        }
        sb.append(", ");
        sb.append("signature:");
        if (this.signature == null) {
            sb.append("null");
        } else {
            sb.append(this.signature);
        }
        sb.append(", ");
        sb.append("importTime:");
        sb.append(this.importTime);
        sb.append(", ");
        sb.append("attribute:");
        sb.append(this.attribute);
        sb.append(", ");
        sb.append("source:");
        if (this.source == null) {
            sb.append("null");
        } else {
            sb.append(this.source);
        }
        sb.append(")");
        return sb.toString();
    }

    public void writeTo(TarsOutputStream _os) {
        if (null != data) {
            _os.write(data, 1);
        }
        if (null != dataHash) {
            _os.write(dataHash, 2);
        }
        if (null != signature) {
            _os.write(signature, 3);
        }
        _os.write(importTime, 4);
        _os.write(attribute, 5);
        if (null != source) {
            _os.write(source, 6);
        }
    }

    static TransactionData cache_data;

    static {
        cache_data = new TransactionData();
    }

    static byte[] cache_dataHash;

    static {
        cache_dataHash = new byte[1];
        byte var_2 = (byte) 0;
        cache_dataHash[0] = var_2;
    }

    static byte[] cache_signature;

    static {
        cache_signature = new byte[1];
        byte var_3 = (byte) 0;
        cache_signature[0] = var_3;
    }

    public void readFrom(TarsInputStream _is) {
        this.data = (TransactionData) _is.read(cache_data, 1, false);
        this.dataHash = (byte[]) _is.read(cache_dataHash, 2, false);
        this.signature = (byte[]) _is.read(cache_signature, 3, false);
        this.importTime = _is.read(importTime, 4, false);
        this.attribute = _is.read(attribute, 5, false);
        this.source = _is.readString(6, false);
    }
}
