package org.fisco.bcos.sdk.v3.test.codec;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.math.BigInteger;
import java.util.Collections;
import org.fisco.bcos.sdk.v3.codec.datatypes.generated.*;
import org.junit.Test;

/**
 * Coverage for the generated fixed-width ABI datatypes (Bytes1..32, Uint8..256, Int8..256) and
 * StaticArray1..32/128: exercises the DEFAULT static initializers and every public constructor.
 */
public class GeneratedTypesTest {

    @Test
    public void testBytes() {
        assertNotNull(Bytes1.DEFAULT);
        assertEquals(1, new Bytes1(new byte[1]).getValue().length);
        assertNotNull(Bytes2.DEFAULT);
        assertEquals(2, new Bytes2(new byte[2]).getValue().length);
        assertNotNull(Bytes3.DEFAULT);
        assertEquals(3, new Bytes3(new byte[3]).getValue().length);
        assertNotNull(Bytes4.DEFAULT);
        assertEquals(4, new Bytes4(new byte[4]).getValue().length);
        assertNotNull(Bytes5.DEFAULT);
        assertEquals(5, new Bytes5(new byte[5]).getValue().length);
        assertNotNull(Bytes6.DEFAULT);
        assertEquals(6, new Bytes6(new byte[6]).getValue().length);
        assertNotNull(Bytes7.DEFAULT);
        assertEquals(7, new Bytes7(new byte[7]).getValue().length);
        assertNotNull(Bytes8.DEFAULT);
        assertEquals(8, new Bytes8(new byte[8]).getValue().length);
        assertNotNull(Bytes9.DEFAULT);
        assertEquals(9, new Bytes9(new byte[9]).getValue().length);
        assertNotNull(Bytes10.DEFAULT);
        assertEquals(10, new Bytes10(new byte[10]).getValue().length);
        assertNotNull(Bytes11.DEFAULT);
        assertEquals(11, new Bytes11(new byte[11]).getValue().length);
        assertNotNull(Bytes12.DEFAULT);
        assertEquals(12, new Bytes12(new byte[12]).getValue().length);
        assertNotNull(Bytes13.DEFAULT);
        assertEquals(13, new Bytes13(new byte[13]).getValue().length);
        assertNotNull(Bytes14.DEFAULT);
        assertEquals(14, new Bytes14(new byte[14]).getValue().length);
        assertNotNull(Bytes15.DEFAULT);
        assertEquals(15, new Bytes15(new byte[15]).getValue().length);
        assertNotNull(Bytes16.DEFAULT);
        assertEquals(16, new Bytes16(new byte[16]).getValue().length);
        assertNotNull(Bytes17.DEFAULT);
        assertEquals(17, new Bytes17(new byte[17]).getValue().length);
        assertNotNull(Bytes18.DEFAULT);
        assertEquals(18, new Bytes18(new byte[18]).getValue().length);
        assertNotNull(Bytes19.DEFAULT);
        assertEquals(19, new Bytes19(new byte[19]).getValue().length);
        assertNotNull(Bytes20.DEFAULT);
        assertEquals(20, new Bytes20(new byte[20]).getValue().length);
        assertNotNull(Bytes21.DEFAULT);
        assertEquals(21, new Bytes21(new byte[21]).getValue().length);
        assertNotNull(Bytes22.DEFAULT);
        assertEquals(22, new Bytes22(new byte[22]).getValue().length);
        assertNotNull(Bytes23.DEFAULT);
        assertEquals(23, new Bytes23(new byte[23]).getValue().length);
        assertNotNull(Bytes24.DEFAULT);
        assertEquals(24, new Bytes24(new byte[24]).getValue().length);
        assertNotNull(Bytes25.DEFAULT);
        assertEquals(25, new Bytes25(new byte[25]).getValue().length);
        assertNotNull(Bytes26.DEFAULT);
        assertEquals(26, new Bytes26(new byte[26]).getValue().length);
        assertNotNull(Bytes27.DEFAULT);
        assertEquals(27, new Bytes27(new byte[27]).getValue().length);
        assertNotNull(Bytes28.DEFAULT);
        assertEquals(28, new Bytes28(new byte[28]).getValue().length);
        assertNotNull(Bytes29.DEFAULT);
        assertEquals(29, new Bytes29(new byte[29]).getValue().length);
        assertNotNull(Bytes30.DEFAULT);
        assertEquals(30, new Bytes30(new byte[30]).getValue().length);
        assertNotNull(Bytes31.DEFAULT);
        assertEquals(31, new Bytes31(new byte[31]).getValue().length);
        assertNotNull(Bytes32.DEFAULT);
        assertEquals(32, new Bytes32(new byte[32]).getValue().length);
    }

    @Test
    public void testUint() {
        assertNotNull(Uint8.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint8(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint8(2L).getValue());
        assertNotNull(Uint16.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint16(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint16(2L).getValue());
        assertNotNull(Uint24.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint24(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint24(2L).getValue());
        assertNotNull(Uint32.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint32(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint32(2L).getValue());
        assertNotNull(Uint40.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint40(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint40(2L).getValue());
        assertNotNull(Uint48.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint48(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint48(2L).getValue());
        assertNotNull(Uint56.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint56(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint56(2L).getValue());
        assertNotNull(Uint64.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint64(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint64(2L).getValue());
        assertNotNull(Uint72.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint72(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint72(2L).getValue());
        assertNotNull(Uint80.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint80(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint80(2L).getValue());
        assertNotNull(Uint88.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint88(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint88(2L).getValue());
        assertNotNull(Uint96.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint96(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint96(2L).getValue());
        assertNotNull(Uint104.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint104(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint104(2L).getValue());
        assertNotNull(Uint112.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint112(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint112(2L).getValue());
        assertNotNull(Uint120.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint120(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint120(2L).getValue());
        assertNotNull(Uint128.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint128(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint128(2L).getValue());
        assertNotNull(Uint136.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint136(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint136(2L).getValue());
        assertNotNull(Uint144.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint144(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint144(2L).getValue());
        assertNotNull(Uint152.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint152(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint152(2L).getValue());
        assertNotNull(Uint160.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint160(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint160(2L).getValue());
        assertNotNull(Uint168.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint168(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint168(2L).getValue());
        assertNotNull(Uint176.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint176(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint176(2L).getValue());
        assertNotNull(Uint184.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint184(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint184(2L).getValue());
        assertNotNull(Uint192.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint192(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint192(2L).getValue());
        assertNotNull(Uint200.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint200(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint200(2L).getValue());
        assertNotNull(Uint208.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint208(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint208(2L).getValue());
        assertNotNull(Uint216.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint216(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint216(2L).getValue());
        assertNotNull(Uint224.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint224(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint224(2L).getValue());
        assertNotNull(Uint232.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint232(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint232(2L).getValue());
        assertNotNull(Uint240.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint240(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint240(2L).getValue());
        assertNotNull(Uint248.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint248(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint248(2L).getValue());
        assertNotNull(Uint256.DEFAULT);
        assertEquals(BigInteger.ONE, new Uint256(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(2), new Uint256(2L).getValue());
    }

    @Test
    public void testInt() {
        assertNotNull(Int8.DEFAULT);
        assertEquals(BigInteger.ONE, new Int8(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int8(-1L).getValue());
        assertNotNull(Int16.DEFAULT);
        assertEquals(BigInteger.ONE, new Int16(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int16(-1L).getValue());
        assertNotNull(Int24.DEFAULT);
        assertEquals(BigInteger.ONE, new Int24(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int24(-1L).getValue());
        assertNotNull(Int32.DEFAULT);
        assertEquals(BigInteger.ONE, new Int32(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int32(-1L).getValue());
        assertNotNull(Int40.DEFAULT);
        assertEquals(BigInteger.ONE, new Int40(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int40(-1L).getValue());
        assertNotNull(Int48.DEFAULT);
        assertEquals(BigInteger.ONE, new Int48(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int48(-1L).getValue());
        assertNotNull(Int56.DEFAULT);
        assertEquals(BigInteger.ONE, new Int56(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int56(-1L).getValue());
        assertNotNull(Int64.DEFAULT);
        assertEquals(BigInteger.ONE, new Int64(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int64(-1L).getValue());
        assertNotNull(Int72.DEFAULT);
        assertEquals(BigInteger.ONE, new Int72(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int72(-1L).getValue());
        assertNotNull(Int80.DEFAULT);
        assertEquals(BigInteger.ONE, new Int80(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int80(-1L).getValue());
        assertNotNull(Int88.DEFAULT);
        assertEquals(BigInteger.ONE, new Int88(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int88(-1L).getValue());
        assertNotNull(Int96.DEFAULT);
        assertEquals(BigInteger.ONE, new Int96(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int96(-1L).getValue());
        assertNotNull(Int104.DEFAULT);
        assertEquals(BigInteger.ONE, new Int104(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int104(-1L).getValue());
        assertNotNull(Int112.DEFAULT);
        assertEquals(BigInteger.ONE, new Int112(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int112(-1L).getValue());
        assertNotNull(Int120.DEFAULT);
        assertEquals(BigInteger.ONE, new Int120(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int120(-1L).getValue());
        assertNotNull(Int128.DEFAULT);
        assertEquals(BigInteger.ONE, new Int128(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int128(-1L).getValue());
        assertNotNull(Int136.DEFAULT);
        assertEquals(BigInteger.ONE, new Int136(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int136(-1L).getValue());
        assertNotNull(Int144.DEFAULT);
        assertEquals(BigInteger.ONE, new Int144(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int144(-1L).getValue());
        assertNotNull(Int152.DEFAULT);
        assertEquals(BigInteger.ONE, new Int152(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int152(-1L).getValue());
        assertNotNull(Int160.DEFAULT);
        assertEquals(BigInteger.ONE, new Int160(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int160(-1L).getValue());
        assertNotNull(Int168.DEFAULT);
        assertEquals(BigInteger.ONE, new Int168(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int168(-1L).getValue());
        assertNotNull(Int176.DEFAULT);
        assertEquals(BigInteger.ONE, new Int176(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int176(-1L).getValue());
        assertNotNull(Int184.DEFAULT);
        assertEquals(BigInteger.ONE, new Int184(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int184(-1L).getValue());
        assertNotNull(Int192.DEFAULT);
        assertEquals(BigInteger.ONE, new Int192(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int192(-1L).getValue());
        assertNotNull(Int200.DEFAULT);
        assertEquals(BigInteger.ONE, new Int200(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int200(-1L).getValue());
        assertNotNull(Int208.DEFAULT);
        assertEquals(BigInteger.ONE, new Int208(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int208(-1L).getValue());
        assertNotNull(Int216.DEFAULT);
        assertEquals(BigInteger.ONE, new Int216(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int216(-1L).getValue());
        assertNotNull(Int224.DEFAULT);
        assertEquals(BigInteger.ONE, new Int224(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int224(-1L).getValue());
        assertNotNull(Int232.DEFAULT);
        assertEquals(BigInteger.ONE, new Int232(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int232(-1L).getValue());
        assertNotNull(Int240.DEFAULT);
        assertEquals(BigInteger.ONE, new Int240(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int240(-1L).getValue());
        assertNotNull(Int248.DEFAULT);
        assertEquals(BigInteger.ONE, new Int248(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int248(-1L).getValue());
        assertNotNull(Int256.DEFAULT);
        assertEquals(BigInteger.ONE, new Int256(BigInteger.ONE).getValue());
        assertEquals(BigInteger.valueOf(-1), new Int256(-1L).getValue());
    }

    @Test
    public void testStaticArray() {
        Uint8 u = new Uint8(BigInteger.ONE);
        assertEquals(1, new StaticArray1<>(Uint8.class, Collections.nCopies(1, u)).getValue().size());
        assertEquals(2, new StaticArray2<>(Uint8.class, Collections.nCopies(2, u)).getValue().size());
        assertEquals(3, new StaticArray3<>(Uint8.class, Collections.nCopies(3, u)).getValue().size());
        assertEquals(4, new StaticArray4<>(Uint8.class, Collections.nCopies(4, u)).getValue().size());
        assertEquals(5, new StaticArray5<>(Uint8.class, Collections.nCopies(5, u)).getValue().size());
        assertEquals(6, new StaticArray6<>(Uint8.class, Collections.nCopies(6, u)).getValue().size());
        assertEquals(7, new StaticArray7<>(Uint8.class, Collections.nCopies(7, u)).getValue().size());
        assertEquals(8, new StaticArray8<>(Uint8.class, Collections.nCopies(8, u)).getValue().size());
        assertEquals(9, new StaticArray9<>(Uint8.class, Collections.nCopies(9, u)).getValue().size());
        assertEquals(10, new StaticArray10<>(Uint8.class, Collections.nCopies(10, u)).getValue().size());
        assertEquals(11, new StaticArray11<>(Uint8.class, Collections.nCopies(11, u)).getValue().size());
        assertEquals(12, new StaticArray12<>(Uint8.class, Collections.nCopies(12, u)).getValue().size());
        assertEquals(13, new StaticArray13<>(Uint8.class, Collections.nCopies(13, u)).getValue().size());
        assertEquals(14, new StaticArray14<>(Uint8.class, Collections.nCopies(14, u)).getValue().size());
        assertEquals(15, new StaticArray15<>(Uint8.class, Collections.nCopies(15, u)).getValue().size());
        assertEquals(16, new StaticArray16<>(Uint8.class, Collections.nCopies(16, u)).getValue().size());
        assertEquals(17, new StaticArray17<>(Uint8.class, Collections.nCopies(17, u)).getValue().size());
        assertEquals(18, new StaticArray18<>(Uint8.class, Collections.nCopies(18, u)).getValue().size());
        assertEquals(19, new StaticArray19<>(Uint8.class, Collections.nCopies(19, u)).getValue().size());
        assertEquals(20, new StaticArray20<>(Uint8.class, Collections.nCopies(20, u)).getValue().size());
        assertEquals(21, new StaticArray21<>(Uint8.class, Collections.nCopies(21, u)).getValue().size());
        assertEquals(22, new StaticArray22<>(Uint8.class, Collections.nCopies(22, u)).getValue().size());
        assertEquals(23, new StaticArray23<>(Uint8.class, Collections.nCopies(23, u)).getValue().size());
        assertEquals(24, new StaticArray24<>(Uint8.class, Collections.nCopies(24, u)).getValue().size());
        assertEquals(25, new StaticArray25<>(Uint8.class, Collections.nCopies(25, u)).getValue().size());
        assertEquals(26, new StaticArray26<>(Uint8.class, Collections.nCopies(26, u)).getValue().size());
        assertEquals(27, new StaticArray27<>(Uint8.class, Collections.nCopies(27, u)).getValue().size());
        assertEquals(28, new StaticArray28<>(Uint8.class, Collections.nCopies(28, u)).getValue().size());
        assertEquals(29, new StaticArray29<>(Uint8.class, Collections.nCopies(29, u)).getValue().size());
        assertEquals(30, new StaticArray30<>(Uint8.class, Collections.nCopies(30, u)).getValue().size());
        assertEquals(31, new StaticArray31<>(Uint8.class, Collections.nCopies(31, u)).getValue().size());
        assertEquals(32, new StaticArray32<>(Uint8.class, Collections.nCopies(32, u)).getValue().size());
        assertEquals(128, new StaticArray128<>(Uint8.class, Collections.nCopies(128, u)).getValue().size());
    }
}
