# This is a config file for amop test

[cryptoMaterial]
certPath = "conf"
# CA cert file path
# caCert = "conf/ca.crt"
# SSL cert file path
# sslCert = "conf/sdk.crt"
# SSL key file path
# sslKey = "conf/sdk.key"
# enSslCert = "conf/gm/gmensdk.crt"
# enSslKey = "conf/gm/gmensdk.key"

[network]
# The peer list to connect
peers=["127.0.0.1:20200", "127.0.0.1:20201"]

# Configure a private topic as a topic message sender.
[[amop]]
topicName = "privTopic"
# Your private key that used to subscriber verification.
privateKey = "conf/amop/consumer_private_key.p12"
password = "123456"


[account]
# The directory where the account private key file is placed in
keyStoreDir = "account"
# The account file path(Default load account from keyStoreDir directory when accountFilePath is not configured)
# accountFilePath = ""
# The storage format of the account, support pem and p12, default is pem
accountFileFormat = "pem"
# The address of the account used to send transactions
# When it's empty, use a randomly generated account to send transactions,
# and the randomly generated account information is stored in tmp sub-directory of keyStoreDir
# accountAddress = ""
# The password used to load the account private key file
# password = ""


[threadPool]
# The size of the thread pool used to process the transaction receipt notification
receiptProcessorThreadSize = "16"

