// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.fisco.bcos.sdk.client.protocol.model;

import com.qq.tars.protocol.tars.TarsInputStream;
import com.qq.tars.protocol.tars.TarsOutputStream;
import com.qq.tars.protocol.tars.annotation.TarsStruct;
import com.qq.tars.protocol.tars.annotation.TarsStructProperty;
import com.qq.tars.protocol.util.TarsUtil;

@TarsStruct
public class Signature {

    @TarsStructProperty(order = 1, isRequire = true)
    public long sealerIndex = 0L;
    @TarsStructProperty(order = 2, isRequire = true)
    public byte[] signature = null;

    public long getSealerIndex() {
        return this.sealerIndex;
    }

    public void setSealerIndex(long sealerIndex) {
        this.sealerIndex = sealerIndex;
    }

    public byte[] getSignature() {
        return this.signature;
    }

    public void setSignature(byte[] signature) {
        this.signature = signature;
    }

    public Signature() {
    }

    public Signature(long sealerIndex, byte[] signature) {
        this.sealerIndex = sealerIndex;
        this.signature = signature;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + TarsUtil.hashCode(this.sealerIndex);
        result = prime * result + TarsUtil.hashCode(this.signature);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Signature)) {
            return false;
        }
        Signature other = (Signature) obj;
        return (
                TarsUtil.equals(this.sealerIndex, other.sealerIndex) &&
                        TarsUtil.equals(this.signature, other.signature)
        );
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Signature(");
        sb.append("sealerIndex:");
        sb.append(this.sealerIndex);
        sb.append(", ");
        sb.append("signature:");
        if (this.signature == null) {
            sb.append("null");
        } else {
            sb.append(this.signature);
        }
        sb.append(")");
        return sb.toString();
    }

    public void writeTo(TarsOutputStream _os) {
        _os.write(this.sealerIndex, 1);
        _os.write(this.signature, 2);
    }

    static byte[] cache_signature;

    static {
        cache_signature = new byte[1];
        byte var_6 = (byte) 0;
        cache_signature[0] = var_6;
    }

    public void readFrom(TarsInputStream _is) {
        this.sealerIndex = _is.read(this.sealerIndex, 1, true);
        this.signature = (byte[]) _is.read(cache_signature, 2, true);
    }

}
